<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYQBK5p7\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYQBK5p7/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYQBK5p7.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYQBK5p7\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYQBK5p7\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'YQBK5p7',
    'container.build_id' => 'c4990fbc',
    'container.build_time' => 1565355443,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYQBK5p7');
