<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGSqEStP\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGSqEStP/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGSqEStP.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGSqEStP\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGSqEStP\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'GSqEStP',
    'container.build_id' => '01bf0d45',
    'container.build_time' => 1565686732,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGSqEStP');
