<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHxX0TJt\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHxX0TJt/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHxX0TJt.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHxX0TJt\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHxX0TJt\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'HxX0TJt',
    'container.build_id' => 'b2296f38',
    'container.build_time' => 1565192135,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHxX0TJt');
